// Copyright Distant Light Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

SPACEGAMESHIPMOVEMENT_API DECLARE_LOG_CATEGORY_EXTERN(SMLogBrain, Log, All);
SPACEGAMESHIPMOVEMENT_API DECLARE_LOG_CATEGORY_EXTERN(SMLogThruster, Log, All);
SPACEGAMESHIPMOVEMENT_API DECLARE_LOG_CATEGORY_EXTERN(SMLogRocket, Log, All);

SPACEGAMESHIPMOVEMENT_API DECLARE_LOG_CATEGORY_EXTERN(SMLogUtils, Log, All);

SPACEGAMESHIPMOVEMENT_API DECLARE_LOG_CATEGORY_EXTERN(SMLogGeneric, Log, All);
SPACEGAMESHIPMOVEMENT_API DECLARE_LOG_CATEGORY_EXTERN(SMLogTemp, Log, All);
